#! /bin/sh

# sxhkd
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 1 > /dev/null
done &

# Wallpaper
feh --bg-fill /home/alliebeans/Pictures/wallpapers/bg_blue_debian_3.png &

# Compositor, notification daemon
picom &
dunst &

# Touchpad settings, Polybar
bash ~/.local/bin/touchpad-settings.sh &
bash ~/.local/bin/polybar.sh &

# bspwm Settings

bspc monitor -d 1 2 3 4 5 6 7

bspc config border_width		2
bspc config border_radius		3
bspc config window_gap			1
bspc config top_padding			28
bspc config right_padding		0
bspc config bottom_padding		0
bspc config left_padding		0
bspc config single_monocle		false
bspc config click_to_focus		false
bspc config split_ratio			0.53
bspc config top_monocle_padding		-28
bspc config right_monocle_padding	0
bspc config bottom_monocle_padding	0
bspc config right_monocle_padding	0
bspc config borderless_monocle		true
bspc config gapless_monocle		true
bspc config focus_by_distance		true
bspc config focus_follows_pointer	true
bspc config history_aware_focus		true
bspc config remove_disabled_monitors	true
bspc config merge_overlapping_monitors	true
bspc config pointer_modifier 		super
bspc config pointer_action1 		move
bspc config pointer_action2 		resize_corner
bspc config pointer_action3 		resize_side

#### BSPWM coloring ####

# background = 	#222223
# foreground = 	#f9f9f9
# gray	= 	#555555
# red 	= 	#ff3e7a
# green = 	#55ff55
# yellow = 	#ffff55
# blue = 	#0006ff
# lilac = 	#ff55e9
# cyan = 	#55ffff
# white	= 	#f8f8f8
# alert	= 	#ff0054

bspc config normal_border_color		
bspc config active_border_color		
bspc config focused_border_color	"#55ffff"
bspc config presel_feedback_color	

bspc rule -a Dialog state=floating center=on

bspc rule -a Code desktop='^3'

bspc rule -a discord desktop='^7'
bspc rule -a Slack desktop='^7'

# Clipboard manager
# xfce4-clipman &

while :; do
    if pgrep -x xfce4-clipman > /dev/null; then
        true
    else
        xfce4-clipman &
    fi
    exit 0
done
